import { Router } from 'express';
const router = Router();

router.get('/agent/help', (req, res) => {
  res.json({
    name: '课表管理系统 API',
    version: '1.7.7',
    description: '面向私人教师的课表管理平台 API，供 AI Agent 访问',
    auth: {
      type: 'API Key 或 JWT Token',
      apiKey: {
        header: 'X-API-Key: <your-key>',
        obtain: '在教师设置页面获取或重新生成',
      },
      jwt: {
        header: 'Authorization: Bearer <token>',
        obtain: 'POST /api/auth/login 返回',
        expiresIn: '默认 7 天,可通过环境变量 JWT_EXPIRES_IN 配置(zeit/ms 格式,如 "1h"/"30d")',
      },
    },
    endpoints: {
      system: {
        'GET /api/agent/help': '获取此帮助文档（公开，无需认证）',
        'GET /api/health': '健康检查（公开，无需认证）',
      },
      auth: {
        'POST /api/auth/register': '注册新教师（需 ALLOW_REGISTRATION=true，注册成功后自动关闭），返回 {token, apiKey}',
        'POST /api/auth/login': '登录（需 username, password），返回 {token}',
        'GET /api/auth/profile': '获取当前教师信息，返回 {id, username, name, apiKey, subjects}',
        'PUT /api/auth/password': '修改密码（需 oldPassword 和 newPassword），返回 {ok:true}',
        'PUT /api/auth/subjects': '更新学科列表（传 subjects 字符串数组），返回 {subjects}',
        'PUT /api/auth/api-key': '重新生成 API Key，返回 {apiKey: <new-key>}',
      },
      classes: {
        'GET /api/classes': '获取班级列表（不含已软删除）；按最后一次排课时间降序排列（无排课的班级排最后）；返回 isDeleted 布尔字段',
        'GET /api/classes?includeDeleted=true': '获取全部班级（含已软删除），isDeleted 字段区分',
        'GET /api/classes/:id': '获取单个班级详情（含 isDeleted），需 ownership 匹配',
        'GET /api/classes/locations/suggest': '获取当前教师所有去重地点名称（从班级默认地点和排课地点合并去重，字母排序）',
        'POST /api/classes': '创建班级（unitPrice 留空时自动匹配阶梯定价），返回完整班级对象（含 id 和 isDeleted）',
        'PUT /api/classes/:id': '更新班级信息，返回完整班级对象',
        'DELETE /api/classes/:id': '删除班级（软删除，排课记录保留），返回 {ok:true}',
        'POST /api/classes/:id/restore': '恢复软删除的班级（deleted=true → false），返回完整班级对象;对未删除班级调用返回 400',
        'GET /api/classes/:classId/students': '获取指定班级的学生列表',
        'POST /api/classes/:classId/students': '在指定班级下创建学生并自动关联到该班级，返回完整学生对象（含 classIds:[classId]）',
        'DELETE /api/classes/:classId/students/:studentId': '从指定班级移除学生（仅解除关联，不删除学生实体），返回 {ok:true}',
      },
      classPricing: {
        'GET /api/classes/:classId/pricing': '获取指定班级的定价历史，按生效日期降序排列；返回定价记录数组',
        'POST /api/classes/:classId/pricing': '新增定价版本（需 studentCount, unitPrice, effectiveFrom；可选 discountAmount, discountReason）；effectiveFrom 重复返回 409；同时更新班级表当前定价字段',
        'PUT /api/classes/:classId/pricing/:pricingId': '修改某条定价记录（变更 effectiveFrom 时查重）；更新后同步班级表当前定价',
        'DELETE /api/classes/:classId/pricing/:pricingId': '删除定价记录（至少保留一条），删除后同步班级表当前定价，返回 {ok:true}',
      },
      students: {
        'GET /api/students': '获取所有学生（含 classIds 数组）；按姓名排序（中文名在前按拼音序，英文名在后按字母序，同名按 ID 倒序即新添加的在前）',
        'GET /api/students/by-class/:classId': '获取指定班级的学生列表',
        'POST /api/students': '创建学生（可通过 classIds 数组同时关联多个班级），返回完整学生对象（含 classIds）',
        'PUT /api/students/:id': '更新学生信息（部分更新：仅写入传入的字段，未传字段保持不变；classIds 变更时全量替换班级关联），返回完整学生对象（含 classIds）',
        'DELETE /api/students/:id': '删除学生（同时清理所有班级关联），返回 {ok:true}',
      },
      schedules: {
        'GET /api/schedules?start=YYYY-MM-DD&end=YYYY-MM-DD': '获取日期范围内的排课（含班级信息）；支持 &studentId=N 按学生所属班级过滤，&limit=N&offset=N 分页（limit 上限 1000，默认不分页）',
        'GET /api/schedules?range=today|tomorrow|week|month': '快捷范围：today=今天，tomorrow=明天，week=本周（周一到周日），month=本月。与 start/end 互斥',
        'GET /api/schedules?start=&end=&classId=1,2,3': '同上，额外按班级 ID 过滤（逗号分隔多个，服务端过滤，节省流量）',
        'GET /api/schedules/:id': '获取单条排课详情（含班级信息）',
        'POST /api/schedules': '创建单次排课，返回完整排课对象（含 class 字段）；如有时间冲突，额外返回 warnings 数组（不阻止创建）',
        'PUT /api/schedules/:id': '更新排课（输入经 express-validator 校验），返回完整排课对象；时间变更时自动重算 durationBilling；如有冲突返回 warnings；变更 classId 时校验目标班级归属且未软删除',
        'DELETE /api/schedules/:id': '删除单条排课',
        'DELETE /api/schedules/batch': '批量删除排课（见 batchDeleteModes）',
        'POST /api/schedules/batch': '批量创建排课（见 batchScheduleModes）',
        'PUT /api/schedules/batch': '批量更新排课时间/地点（见 batchUpdateMode）',
        'GET /api/schedules/summary?start=YYYY-MM-DD&end=YYYY-MM-DD': '课时与收入汇总统计（见 summaryResponse）；同样支持 range 快捷参数；加 &format=csv 返回 CSV 文件（UTF-8 BOM，Excel 兼容）；加 &classId=1 或 &classId=1,2,3 按班级过滤',
        'GET /api/schedules/export?start=YYYY-MM-DD&end=YYYY-MM-DD': '导出排课明细列表（含班级信息）；同样支持 range 快捷参数；加 &classId=1,2,3 逗号分隔过滤班级；加 &format=csv 返回 CSV',
        'GET /api/schedules/free-slots?date=YYYY-MM-DD': '查询单日空闲时段（默认 08:00-23:00；可用 after=HH:MM&before=HH:MM 限制时段;不支持跨午夜,after≥before 返回 400）；返回 {date, slots:[{start,end}]}',
        'GET /api/schedules/free-slots?date=&minDuration=60': '只返回连续可用 ≥60 分钟的时段，适合约课筛选',
        'GET /api/schedules/free-slots?start=YYYY-MM-DD&end=YYYY-MM-DD': '查询多日空闲时段（同样支持 after/before/minDuration）；返回 [{date, slots:[{start,end}]}]（仅含有时段的日期）',
        'GET /api/schedules/conflicts?start=YYYY-MM-DD&end=YYYY-MM-DD&limit=N': '查询冲突排课分组（默认今天起60天，limit 上限100，默认20）；加 &classId=1,2,3 逗号分隔按班级过滤',
      },
      semesters: {
        'GET /api/semesters': '获取学期列表',
        'POST /api/semesters': '创建学期，返回完整学期对象',
        'PUT /api/semesters/:id': '更新学期，返回完整学期对象',
        'DELETE /api/semesters/:id': '删除学期，返回 {ok:true}',
      },
      holidays: {
        'GET /api/holidays': '获取所有节假日和调休记录',
        'GET /api/holidays/:year': '获取指定年份的节假日',
        'POST /api/holidays': '添加节假日/调休（需 date, type: holiday|workday, name），返回完整节假日对象',
        'PUT /api/holidays/:id': '更新节假日记录（变更日期时校验不与已有记录重复），返回完整节假日对象',
        'DELETE /api/holidays/:id': '删除节假日记录，返回 {ok:true}',
        'POST /api/holidays/batch': '批量导入节假日（需 items 数组），返回 {count: N}',
      },
      pricingTiers: {
        'GET /api/pricing-tiers': '获取定价阶梯列表',
        'POST /api/pricing-tiers': '创建定价阶梯，返回完整阶梯对象',
        'PUT /api/pricing-tiers/:id': '更新定价阶梯，返回完整阶梯对象',
        'DELETE /api/pricing-tiers/:id': '删除定价阶梯，返回 {ok:true}',
      },
      images: {
        'GET /api/schedule-image?start=YYYY-MM-DD&end=YYYY-MM-DD': '生成周课表 PNG 图片（返回 image/png），支持任意时间范围；教师无班级时返回 404 {error:"No classes"}；渲染失败时返回 500 {error:"Image generation failed"}',
        'GET /api/schedule-image?range=today|tomorrow|week|month': '快捷范围，与 GET /api/schedules 的 range 参数一致',
        'GET /api/schedule-image?start=&end=&theme=light|dark|auto': 'theme=light 强制浅色，dark 强制深色，auto（默认）按小时自动切换（7:00-19:00 浅色，其余深色）',
        'GET /api/schedule-image?start=&end=&rowH=N': '每小时行高像素（16-60，默认 40），增大后文字更清晰，图片更高',
        'GET /api/schedule-image?start=&end=&scale=N': '整体缩放因子（0.25-3，默认 2），scale=1 适合手机查看，scale=0.5 更小体积',
        'GET /api/schedule-image?start=&end=&highlight=YYYY-MM-DD': '高亮指定日期列（黄色边框），适合截给家长看某天课表',
        'GET /api/schedule-image/monthly?year=Y&month=M': '生成月课表日历网格 PNG 图片（返回 image/png）；month=0-11（0=1月）；支持 theme 参数（同周课表）',
        'GET /api/schedule-image/monthly?year=Y&month=M&endYear=Y&endMonth=M': '生成多个月份的月课表图片（纵向堆叠），endYear/endMonth 为可选结束范围',
        'GET /api/schedule-image/yearly?year=Y': '生成年课表概览 PNG 图片（返回 image/png），12 个月卡片 + 年度统计',
        'GET /api/schedule-image/yearly?year=Y&endYear=Y': '生成多个年份的年课表图片（纵向堆叠），endYear 为可选结束年份',
      },
      backup: {
        'GET /api/backup': '导出教师全量数据为 JSON，返回 {version:1, timestamp, classes, students, classStudents, schedules, semesters, holidays, pricingTiers, classPricing, auditLog}，触发浏览器下载',
        'POST /api/backup/restore': '从备份 JSON 原子还原（先清空再写入，事务保证）；校验 version 字段必须为 1；teacherId 强制覆盖为当前认证教师；还原范围包括 classes、pricingTiers、students、classStudents、schedules、holidays、semesters、classPricing、auditLog；自动校验 schedules、classStudents、classPricing 关联的 classId 是否存在于恢复后的班级中，classStudents 同时校验 studentId 是否存在，无效关联自动跳过;非数组字段按空数组处理;事务失败返回 500 含具体原因(原数据保留);成功返回 {ok:true, restored:{classes,students,schedules,semesters,auditLog}}（restored 仅统计这 5 项，其余表同样已还原但不计数字段中）',
      },
      auditLog: {
        'GET /api/audit-log': '查询操作日志（默认最新 100 条,按 id 倒序;返回的 beforeData/afterData 已 JSON.parse 还原为对象）',
        'GET /api/audit-log?limit=N': '最多返回 N 条（默认 100,上限 500,负数/NaN 自动 clamp）',
        'GET /api/audit-log?table=X': '按数据表过滤,枚举: schedules/classes/students/holidays/class_students/pricing_tiers/semesters/teachers/class_pricing;非法值返回 400',
        'GET /api/audit-log?action=X': '按操作类型过滤,枚举: CREATE/UPDATE/DELETE/BATCH_CREATE/BATCH_UPDATE/BATCH_DELETE;非法值返回 400',
      },
    },
    batchScheduleModes: {
      semester: {
        description: '按学期 + 每周几自动生成排课，自动跳过法定节假日和用户自定义假期',
        params: {
          classId: '班级 ID（必填）',
          semesterId: '学期 ID（必填）',
          weekday: '星期几，0=周日，1=周一，...，6=周六（必填）',
          startTime: '开始时间 HH:MM（必填）',
          endTime: '结束时间 HH:MM（必填）',
          durationBilling: '计费时长分钟，留空自动计算（可选）',
          preview: '布尔值（可选，默认 false），true 时仅返回 {count, dates} 不实际创建',
        },
        response: '{ count: N, ids: [...] }；preview=true 时返回 {count, dates}',
      },
      dates: {
        description: '按指定日期列表批量排课，不自动跳过节假日；日期跨学期边界（部分在学期内、部分在学期外）时返回 400 错误，请分批操作',
        params: {
          classId: '班级 ID（必填）',
          dates: '日期数组 ["YYYY-MM-DD", ...]（必填）',
          startTime: '开始时间 HH:MM（必填）',
          endTime: '结束时间 HH:MM（必填）',
          durationBilling: '计费时长分钟，留空自动计算（可选）',
          preview: '布尔值（可选，默认 false），true 时仅返回 {count, dates} 不实际创建',
        },
        response: '{ count: N, ids: [...] }；preview=true 时返回 {count, dates} 仅预览不创建；日期跨学期时返回 400',
      },
    },
    batchDeleteModes: {
      byIds: {
        description: '按排课 ID 数组精确删除；默认仅删除学期内的排课，跨学期时自动过滤并返回提示；dryRun=true 时仅返回匹配记录不执行删除',
        body: '{ ids: [1, 2, 3, ...], semesterOnly: true|false (可选,默认 true), dryRun: true|false (可选,默认 false) }',
        response: '{ count: N, ids: [...] }；跨学期被过滤时附加 semesterFiltered 与 hint 字段',
      },
      byClassId: {
        description: '按班级 + 起始日期删除（只删 date >= fromDate 的排课；默认仅删除学期内的排课，跨学期时自动过滤并返回提示）',
        body: '{ classId: N, fromDate: "YYYY-MM-DD", semesterOnly: true|false (可选,默认 true), dryRun: true|false (可选,默认 false) }',
        response: '{ count: N, ids: [...] }；跨学期被过滤时附加 semesterFiltered 与 hint 字段',
      },
      byDateRange: {
        description: '按日期范围删除（可附加 classId 只删指定班级；默认仅删除学期内的排课）',
        body: '{ start: "YYYY-MM-DD", end: "YYYY-MM-DD", classId: N (可选), semesterOnly: true|false (可选,默认 true), dryRun: true|false (可选,默认 false) }',
        response: '{ count: N, ids: [...] }；跨学期被过滤时附加 semesterFiltered 与 hint 字段',
      },
    },
    batchUpdateMode: {
      description: 'PUT /api/schedules/batch — 批量修改同一班级在指定范围内的排课的时间或地点',
      params: {
        classId: '班级 ID（必填）',
        fromDate: '起始日期 YYYY-MM-DD（含，可选）；只修改该日期及之后的课。fromDate、toDate 与 weekday 至少传一个',
        toDate: '截止日期 YYYY-MM-DD（含，可选）；只修改该日期及之前的课。未传 fromDate 时下界默认为今天。fromDate、toDate 与 weekday 至少传一个',
        weekday: '星期几，0=周日…6=周六（可选）；只修改该星期几的课。省略则匹配所有星期几。fromDate、toDate 与 weekday 至少传一个',
        semesterOnly: '跨学期保护开关（boolean，默认 true）；只在候选记录"部分在学期内、部分在学期外"时才生效，过滤掉学期外的部分。全部在学期内或全部在学期外时本参数不影响结果。设为 false 强制不过滤',
        updates: '要修改的字段对象（必填）；仅允许以下字段：startTime, endTime, durationBilling, locationName, locationLat, locationLng',
      },
      allowedUpdateFields: ['startTime', 'endTime', 'durationBilling', 'locationName', 'locationLat', 'locationLng'],
      note: 'startTime/endTime 变更时自动重算 durationBilling（除非 updates 中显式传 durationBilling）；不在 allowedUpdateFields 中的字段静默忽略',
      response: '{ count: N, ids: [...] }；跨学期被过滤时附加 semesterFiltered 与 hint 字段',
      example: '{"classId":1,"fromDate":"2026-05-01","weekday":6,"updates":{"startTime":"14:00","endTime":"16:00"}}',
    },
    summaryResponse: {
      description: 'GET /api/schedules/summary 返回结构；支持 &classId=N（逗号分隔多个）按班级过滤',
      fields: {
        count: '排课总次数',
        hours: '总教学课时（小时，含小数）',
        revenue: '预估总收入（元）',
        byClass: '按班级分组 [{classId, name, subject, grade, count, hours, revenue}]，按收入降序',
        bySubject: '按学科分组 [{subject, count, hours, revenue}]，按次数降序',
        byGrade: '按年级分组 [{grade, count, hours, revenue}]，按次数降序',
      },
      revenueFormula: '按排课日期匹配 class_pricing 中的对应版本：(classPricing.unitPrice × classPricing.studentCount - classPricing.discountAmount) × (durationBilling 分钟 / 60)；当日无 class_pricing 时回退到班级表当前值；discount 大于课时基价时收入会为负数',
    },
    dataModels: {
      class: {
        name: '班级名称（必填）',
        grade: '年级：初一/初二/初三/高一/高二/高三/大学（必填）',
        subject: '学科（必填）',
        studentCount: '学生人数（必填）',
        unitPrice: '单价（元/人/小时），留空自动匹配阶梯定价',
        discountAmount: '优惠金额（默认 0）',
        discountReason: '优惠原因（可选）',
        isCompetition: '是否竞赛课（boolean，默认 false）',
        defaultLocationName: '默认上课地点名称',
        defaultLocationLat: '纬度',
        defaultLocationLng: '经度',
      },
      student: {
        name: '姓名（必填）',
        birthDate: '出生日期 YYYY 或 YYYY-MM-DD（可选,空字符串等同不填）',
        phone: '学生电话（可选,11 位手机号；空字符串等同不填）',
        parentName: '父母姓名（可选,自由文本）',
        parentPhone: '父母联系方式（可选,11 位手机号；空字符串等同不填）',
        note: '备注（可选,自由文本）',
        classIds: '所属班级 ID 数组（创建/更新时可关联多个班级；只接受当前教师拥有且未软删除的班级,无效 ID 静默跳过）',
      },
      schedule: {
        classId: '班级 ID（必填）',
        date: '上课日期 YYYY-MM-DD（必填）',
        startTime: '开始时间 HH:MM（必填）',
        endTime: '结束时间 HH:MM（必填）',
        durationBilling: '计费时长（分钟），默认由 endTime - startTime 自动计算，手动指定时覆盖',
        locationName: '上课地点名称（默认继承班级默认地点）',
        locationLat: '纬度',
        locationLng: '经度',
        createdAt: '创建时间（YYYY-MM-DD HH:MM:SS 格式，由数据库自动填写）',
      },
      classPricing: {
        classId: '所属班级 ID',
        studentCount: '学生人数',
        unitPrice: '单价（元/人/小时）',
        discountAmount: '优惠金额（默认 0）',
        discountReason: '优惠原因',
        effectiveFrom: '生效日期（YYYY-MM-DD）；排课定价按此日期匹配，同一班级同一天唯一',
      },
      pricingTier: {
        minStudents: '最小学生人数',
        maxStudents: '最大学生人数',
        pricePerStudentPerHour: '每人每小时单价（元）',
      },
      semester: {
        name: '学期名称（如 "2026春季"）',
        type: '类型：spring / fall / winter / summer',
        startDate: '开始日期 YYYY-MM-DD',
        endDate: '结束日期 YYYY-MM-DD',
      },
      holiday: {
        date: '日期 YYYY-MM-DD',
        type: 'holiday（节假日）或 workday（调休上班）',
        name: '名称（如 "春节"、"国庆调休"）',
      },
      auditLogEntry: {
        id: '日志 ID',
        teacherId: '教师 ID',
        timestamp: '操作时间（ISO 8601）',
        action: 'CREATE / UPDATE / DELETE / BATCH_CREATE / BATCH_UPDATE / BATCH_DELETE',
        tableName: '操作的数据表（schedules / classes / students / holidays / class_students / pricing_tiers / semesters / teachers / class_pricing）',
        recordId: '被操作记录的 ID（批量操作时为 null）',
        beforeData: '操作前数据对象（CREATE / BATCH_CREATE 时为 null）',
        afterData: '操作后数据对象（DELETE 时为 null；BATCH_DELETE 含 count 和 ids；BATCH_UPDATE 含 count, ids, classId, updates）',
      },
    },
    notes: [
      '【写接口返回体约定】单资源 POST/PUT 统一返回完整资源对象（含 id 与所有派生字段，如 classes 的 isDeleted、students 的 classIds、schedules 的 class 与 warnings）；DELETE 单资源返回 {ok:true}；批量端点（POST/PUT/DELETE /api/*/batch、POST /api/holidays/batch）返回 {count, ids?, ...}；前端不依赖 ok 字段，只看 HTTP 状态码',
      '所有 JSON 响应的 Content-Type 均为 application/json; charset=utf-8（CSV 导出时为 text/csv; charset=utf-8）',
      '请求体大小限制 50 MB(覆盖备份还原最大场景);超出返回 413',
      '排课冲突不会被服务端阻止，前端并排显示并红色高亮；可用 GET /api/schedules/conflicts 查询已有冲突',
      'GET /api/schedules、summary、export 均支持 range=today|tomorrow|week|month 快捷参数（与 start/end 互斥），week=本周周一到周日',
      '日期相关接口（range、free-slots、conflicts 的 today 默认值等）基于服务器系统时区；部署时请确认 TZ=Asia/Shanghai 或等值中国时区。所有"今天"判断(批量排课、图片高亮、备份文件名)统一使用本地时区,不依赖 UTC',
      'free-slots 支持 after/before 参数限制查询时段（如 after=14:00&before=21:00），优先级高于 dayStart/dayEnd；支持 minDuration=N 过滤（只返回连续可用 ≥N 分钟的时段）',
      'POST/PUT /api/schedules 返回的排课对象可能含 warnings 字段（数组），包含同一时段的冲突排课信息（id/classId/className/startTime/endTime），不阻止创建/更新',
      'conflicts 返回 {total, groups:[{date, schedules:[...]}]}，total = groups.length（冲突组数量,不是涉事排课条数）；schedules 为同一天内互相重叠的排课组（每组至少 2 条）',
      'POST /api/schedules 和 PUT /api/schedules/:id 均返回完整排课对象（含 class 字段），可直接判断是否存在冲突',
      'durationBilling 默认由 endTime - startTime 自动计算，跨午夜时自动处理',
      '法定节假日数据可通过 POST /api/holidays/batch 批量导入，批量排课（学期模式）自动跳过',
      '批量排课学期模式跳过假期的优先级:用户 workday 调休 > 用户 holiday > 内置法定假期。即:同一日期若同时存在内置 holiday + 用户 workday,则视为上班日(可排课);用户加 holiday 在内置 workday 上则视为节假日(跳过)。',
      '内置法定假期数据覆盖 2025-2027 三年;2028+ 年份需通过 POST /api/holidays/batch 自行导入或在 GET /api/holidays 中 type=holiday 添加,否则批量排课不会自动跳过',
      '批量端点 dates/items 数组长度上限 365 条,超出返回 400',
      '图片导出支持任意时间范围，天数越多图片越宽；生成失败时返回 JSON {error}（不含内部 detail）；rowH 范围 16-60，默认 40；班级名/地点名等用户输入在生成 HTML 时统一 HTML 转义,无 XSS 风险',
      'PUT /api/schedules/batch 只允许修改时间和地点字段，classId/date 等核心字段不可批量篡改',
      'GET /api/schedules/summary 和 GET /api/schedules/export 均支持 &format=csv，响应含 UTF-8 BOM，Excel 直接打开不乱码;以 = + - @ \\t \\r 开头的单元格自动加单引号前缀防御 CSV 公式注入',
      'GET /api/backup 返回全量 JSON（含 version 字段，当前为 1）；POST /api/backup/restore 校验 version 必须匹配，不匹配返回 400；恢复前自动保存快照到 ./data/backup_pre_restore_<timestamp>.json（非致命,失败不阻塞还原），恢复过程中 teacherId 强制绑定当前账号；schedules、classStudents、classPricing 关联会校验 classId 是否存在于恢复数据中，classStudents 额外校验 studentId，无效关联自动跳过',
      '学生可属于多个班级，通过 classIds 数组关联；DELETE /api/students/:id 删除学生实体并清理所有关联，DELETE /api/classes/:classId/students/:studentId 仅从指定班级移除。POST /api/classes/:classId/students 接受 name/birthDate/phone/parentPhone/parentName/note 字段（与 POST /api/students 一致，但不接受 classIds）',
      'PUT /api/students/:id 采用部分更新语义：仅写入请求体中包含且值非 undefined 的字段，未传字段保持原值；classIds 传入时全量替换班级关联',
      'POST/PUT /api/holidays 变更日期时会检查是否与已有节假日记录重复，重复则返回 409 {error:"该日期已有记录"}',
      '审计日志（audit_log）覆盖：排课 CREATE/UPDATE/DELETE/BATCH_CREATE/BATCH_UPDATE/BATCH_DELETE；班级 CREATE/UPDATE/DELETE（含恢复操作）；学生 CREATE/UPDATE/DELETE（含子路由 POST/DELETE /api/classes/:cid/students）；节假日 CREATE/UPDATE/DELETE/BATCH_CREATE；定价阶梯 CREATE/UPDATE/DELETE；学期 CREATE/UPDATE/DELETE；班级定价（class_pricing）CREATE/UPDATE/DELETE；教师（teachers）API Key 轮换/密码修改/学科更新。日志超过 10000 条时自动删除最旧记录',
      '注册成功后系统自动将 ALLOW_REGISTRATION 设为 false，单用户设计',
      'rate limiting：仅 POST /api/auth/register 与 POST /api/auth/login 启用 60 次/分钟限速；其它认证后端点（含 PUT /api/auth/api-key、PUT /api/auth/password 与各资源 CRUD）不受 rate limit 保护',
      '所有写接口均使用 express-validator 校验输入（POST /api/backup/restore 和 PUT /api/auth/api-key 因无标准字段或 payload 特殊，采用手动校验），校验失败返回 400 {error: "提示信息"}，详见下方 validationRules',
      'GET /api/schedules 和 GET /api/schedules/export 的 classId 参数支持逗号分隔多值（如 classId=1,2,3），与 summary 端点一致',
      '批量创建/删除/更新返回 {count, ids} 汇总；单条操作（GET/POST/PUT）返回完整的排课对象（含 class 字段）',
      'classId 多值过滤统一使用逗号分隔格式（如 classId=1,2,3），不支持重复同名参数形式（classId=1&classId=2）',
      'DELETE /api/schedules/batch 支持三种模式：byIds（ID数组）、byClassId（班级+起始日期+学期保护，默认仅删学期内排课）、byDateRange（日期范围，可选 classId，默认学期保护）；三种模式均支持 dryRun=true 仅预览不删除；所有模式均返回 {count, ids}',
      'GET /api/holidays/:year 返回指定年份的节假日记录',
      '批量排课学期模式起始日：max(今天, 学期开始日期)，确保不会生成历史排课',
      '学生创建/更新接口的可选字符串字段（phone、parentPhone、birthDate）接受空字符串 ""，等同于不传',
      '班级创建时自动生成一条 class_pricing 初始记录（effectiveFrom=当天）；定价版本按 effectiveFrom 日期匹配排课收入计算，支持班级定价随时间分段变更；修改定价不会影响历史收入',
      'class_pricing 变更时自动同步到 classes 表：新增/修改/删除定价记录时自动更新班级表的当前定价字段；班级表字段仅作展示和默认值使用，收入计算以 class_pricing 为准',
    ],
    validationRules: {
      auth: {
        register: { username: '3-20位字母数字', password: '至少6位', name: '必填' },
        login: { username: '必填', password: '必填' },
        changePassword: { oldPassword: '必填', newPassword: '至少6位' },
        updateSubjects: { subjects: '字符串数组，每项1-20字符' },
      },
      classes: {
        create: { name: '必填', grade: '枚举：初一/初二/初三/高一/高二/高三/大学', subject: '必填', studentCount: '≥1整数', unitPrice: '可选≥0', discountAmount: '可选≥0', discountReason: '可选自由文本', isCompetition: '可选布尔', defaultLocationName: '可选字符串', defaultLocationLat: '可选数字', defaultLocationLng: '可选数字' },
        update: { name: '可选（不为空）', grade: '可选枚举', subject: '可选（不为空）', studentCount: '可选≥1', unitPrice: '可选≥0', discountAmount: '可选≥0', discountReason: '可选自由文本', isCompetition: '可选布尔', defaultLocationName: '可选字符串', defaultLocationLat: '可选数字', defaultLocationLng: '可选数字' },
        addStudent: { name: '必填', birthDate: 'YYYY 或 YYYY-MM-DD（可选，空字符串等同不填）', phone: '可选 11 位手机号', parentPhone: '可选 11 位手机号', parentName: '可选自由文本', note: '可选自由文本' },
      },
      students: {
        create: { name: '必填', phone: '11位手机号（可选，空字符串等同不填）', parentPhone: '11位手机号（可选，空字符串等同不填）', birthDate: 'YYYY 或 YYYY-MM-DD（可选，空字符串等同不填）', classIds: '整数数组（可选）', parentName: '可选自由文本', note: '可选自由文本' },
        update: { name: '可选', phone: '可选11位', parentPhone: '可选11位', parentName: '可选自由文本', birthDate: '可选 YYYY 或 YYYY-MM-DD', note: '可选自由文本', classIds: '可选整数数组（无效班级 ID 静默跳过）' },
      },
      schedules: {
        create: { classId: '整数必填', date: 'YYYY-MM-DD 必填', startTime: 'HH:MM 必填', endTime: 'HH:MM 必填', durationBilling: '可选非负整数（默认由 endTime-startTime 自动计算）', locationName: '可选字符串（默认继承班级默认地点）', locationLat: '可选数字', locationLng: '可选数字' },
        update: { classId: '可选整数（变更时校验归属和软删除）', date: '可选 YYYY-MM-DD', startTime: '可选 HH:MM', endTime: '可选 HH:MM', durationBilling: '可选非负整数（startTime/endTime 变更且未显式传时自动重算）', locationName: '可选字符串', locationLat: '可选数字', locationLng: '可选数字' },
        batchCreate: { classId: '整数必填', startTime: 'HH:MM 必填', endTime: 'HH:MM 必填', dates: '可选数组,最多 365 项', semesterId: '可选,与 weekday 配合学期模式', weekday: '可选 0-6,与 semesterId 配合', durationBilling: '可选非负整数（默认由 endTime-startTime 自动计算）', preview: '布尔值可选（默认 false,true 时仅返回 {count,dates} 预览不创建）' },
        batchUpdate: { classId: '整数必填', fromDate: 'YYYY-MM-DD 可选', toDate: 'YYYY-MM-DD 可选', weekday: '0-6 可选（省略匹配所有星期几）', semesterOnly: 'boolean 可选（默认 true）', updates: '对象必填', note: 'fromDate、toDate 与 weekday 至少传一个' },
        batchDelete: { ids: '整数数组（必填,byIds模式）', start: 'YYYY-MM-DD（byDateRange模式必填）', end: 'YYYY-MM-DD（byDateRange模式必填）', classId: '正整数（byClassId模式必填;byDateRange模式可选过滤）', fromDate: 'YYYY-MM-DD（byClassId模式必填）', semesterOnly: 'boolean 可选（默认 true,仅删学期内排课）', dryRun: 'boolean 可选（默认 false,true 时仅预览不删除）' },
      },
      semesters: {
        create: { name: '必填', type: '枚举：spring/fall/winter/summer（对应 春季/秋季/暑假/寒假）', startDate: 'YYYY-MM-DD 必填', endDate: 'YYYY-MM-DD 必填,须不早于 startDate' },
        update: { name: '可选', type: '可选枚举', startDate: '可选', endDate: '可选,若同时传 startDate 则校验不早于该值' },
      },
      holidays: {
        create: { date: 'YYYY-MM-DD 必填', type: '枚举：holiday/workday', name: '必填非空' },
        update: { date: '可选 YYYY-MM-DD（变更时校验不与已有记录重复，重复返回 409）', type: '可选枚举', name: '可选,传则不能为空字符串' },
        batch: { items: '数组,最多 365 项;同一 date 仅插入第一条（重复跳过）' },
      },
      pricingTiers: {
        create: { minStudents: '≥1整数', maxStudents: '≥1整数,须不小于 minStudents', pricePerStudentPerHour: '>0 数字' },
        update: { minStudents: '可选≥1', maxStudents: '可选≥1,变更时仍校验不小于 minStudents', pricePerStudentPerHour: '可选>0' },
      },
      classPricing: {
        create: { studentCount: '≥1 整数必填', unitPrice: '≥0 数字必填', effectiveFrom: 'YYYY-MM-DD 必填，同班级同日期不可重复', discountAmount: '可选≥0', discountReason: '可选自由文本' },
        update: { studentCount: '可选≥1', unitPrice: '可选≥0', effectiveFrom: '可选 YYYY-MM-DD，变更时查重', discountAmount: '可选≥0', discountReason: '可选自由文本' },
      },
    },
    examples: {
      '登录获取 token': 'POST /api/auth/login {"username":"xxx","password":"xxx"}',
      '获取本周课表（快捷）': 'GET /api/schedules?range=week',
      '获取今日课表': 'GET /api/schedules?range=today',
      '获取本月课表': 'GET /api/schedules?range=month',
      '获取本周课表（显式日期）': 'GET /api/schedules?start=2026-04-27&end=2026-05-03',
      '获取指定班级本周课表': 'GET /api/schedules?start=2026-04-27&end=2026-05-03&classId=1',
      '获取多个班级本周课表': 'GET /api/schedules?start=2026-04-27&end=2026-05-03&classId=1,2,3',
      '获取单条排课': 'GET /api/schedules/42',
      '本月收入汇总（JSON）': 'GET /api/schedules/summary?start=2026-05-01&end=2026-05-31',
      '本月收入汇总（按班级过滤）': 'GET /api/schedules/summary?start=2026-05-01&end=2026-05-31&classId=1',
      '本月收入汇总（CSV 下载）': 'GET /api/schedules/summary?start=2026-05-01&end=2026-05-31&format=csv',
      '导出排课明细（JSON）': 'GET /api/schedules/export?start=2026-05-01&end=2026-05-31',
      '导出排课明细（CSV 下载）': 'GET /api/schedules/export?start=2026-05-01&end=2026-05-31&format=csv',
      '批量调整排课时间（周六从5月起改为14:00-16:00）': 'PUT /api/schedules/batch {"classId":1,"fromDate":"2026-05-01","weekday":6,"updates":{"startTime":"14:00","endTime":"16:00"}}',
      '生成课表图片（默认）': 'GET /api/schedule-image?start=2026-04-27&end=2026-05-03',
      '生成课表图片（浅色，行高40）': 'GET /api/schedule-image?start=2026-04-27&end=2026-05-03&theme=light&rowH=40',
      '生成2周课表图片（深色）': 'GET /api/schedule-image?start=2026-04-27&end=2026-05-10&theme=dark',
      '批量排课（学期模式）': 'POST /api/schedules/batch {"classId":1,"semesterId":1,"weekday":1,"startTime":"08:00","endTime":"10:00"}',
      '批量排课（日期模式）': 'POST /api/schedules/batch {"classId":1,"dates":["2026-07-01","2026-07-08"],"startTime":"08:00","endTime":"10:00"}',
      '批量删课（ID数组）': 'DELETE /api/schedules/batch {"ids":[10,11,12]}',
      '批量删课（日期范围+班级）': 'DELETE /api/schedules/batch {"classId":1,"start":"2026-05-01","end":"2026-05-31"}',
      '批量删课（班级+起始日期）': 'DELETE /api/schedules/batch {"classId":1,"fromDate":"2026-05-11"}',
      '批量删课（班级+起始日期,忽略学期限制）': 'DELETE /api/schedules/batch {"classId":1,"fromDate":"2026-05-11","semesterOnly":false}',
      '查询空闲时段（全天）': 'GET /api/schedules/free-slots?date=2026-05-06',
      '查询空闲时段（指定时段）': 'GET /api/schedules/free-slots?date=2026-05-06&after=14:00&before=21:00',
      '查询空闲时段（至少60分钟）': 'GET /api/schedules/free-slots?date=2026-05-06&minDuration=60',
      '查询多日空闲时段（指定时段）': 'GET /api/schedules/free-slots?start=2026-05-06&end=2026-05-12&after=14:00&before=22:00',
      '空闲时段响应示例（单日）': '{ date: "2026-05-06", slots: [{ start: "08:00", end: "10:30" }, { start: "12:00", end: "15:00" }] }',
      '空闲时段响应示例（多日）': '[{ date: "2026-05-06", slots: [...] }, { date: "2026-05-07", slots: [...] }]',
      '生成本周课表图片（快捷）': 'GET /api/schedule-image?range=week',
      '生成课表图片（手机缩放）': 'GET /api/schedule-image?range=week&scale=1',
      '生成课表图片（高亮某天）': 'GET /api/schedule-image?range=week&highlight=2026-05-06',
      '获取全部班级（含已删除）': 'GET /api/classes?includeDeleted=true',
      '查询冲突排课': 'GET /api/schedules/conflicts',
      '查询近期冲突（自定义范围）': 'GET /api/schedules/conflicts?start=2026-05-01&end=2026-05-31&limit=50',
      '查询操作日志（最近批量操作）': 'GET /api/audit-log?action=BATCH_UPDATE&limit=20',
      '查询操作日志（最近删除）': 'GET /api/audit-log?table=schedules&action=DELETE&limit=20',
      '创建学生并关联多个班级': 'POST /api/students {"name":"张三","birthDate":"2010","classIds":[1,2]}',
      '在指定班级下创建学生': 'POST /api/classes/1/students {"name":"张三","phone":"13800138000"}',
      '从班级移除学生（不解绑其他班级）': 'DELETE /api/classes/1/students/5',
      '删除学生（级联删除所有关联）': 'DELETE /api/students/5',
      '创建学期': 'POST /api/semesters {"name":"2026春季","type":"spring","startDate":"2026-02-23","endDate":"2026-07-05"}',
      '批量导入节假日': 'POST /api/holidays/batch {"items":[{"date":"2026-01-01","type":"holiday","name":"元旦"}]}',
      '备份全量数据': 'GET /api/backup',
      '还原备份（传 GET /api/backup 的响应体）': 'POST /api/backup/restore <backup-json>',
    },
  });
});

export default router;
