import { Router } from 'express';
const router = Router();

router.get('/agent/help', (req, res) => {
  res.json({
    name: '课表管理系统 API',
    version: '1.6.0',
    description: '面向私人教师的课表管理平台 API，供 AI Agent 访问',
    auth: {
      type: 'API Key 或 JWT Token',
      apiKey: {
        header: 'X-API-Key: <your-key>',
        obtain: '在教师设置页面获取或重新生成',
      },
      jwt: {
        header: 'Authorization: Bearer <token>',
        obtain: 'POST /api/auth/login 返回',
      },
    },
    endpoints: {
      system: {
        'GET /api/agent/help': '获取此帮助文档（公开，无需认证）',
        'GET /api/health': '健康检查（公开，无需认证）',
      },
      auth: {
        'POST /api/auth/register': '注册新教师（需 ALLOW_REGISTRATION=true，注册成功后自动关闭）',
        'POST /api/auth/login': '登录，返回 JWT token',
        'GET /api/auth/profile': '获取当前教师信息（含 subjects 和 apiKey）',
        'PUT /api/auth/password': '修改密码（需 oldPassword 和 newPassword）',
        'PUT /api/auth/subjects': '更新学科列表（传 subjects 字符串数组）',
        'PUT /api/auth/api-key': '重新生成 API Key',
      },
      classes: {
        'GET /api/classes': '获取班级列表（不含已软删除）；返回 isDeleted 布尔字段',
        'GET /api/classes?includeDeleted=true': '获取全部班级（含已软删除），isDeleted 字段区分',
        'POST /api/classes': '创建班级（unitPrice 留空时自动匹配阶梯定价）',
        'PUT /api/classes/:id': '更新班级信息',
        'DELETE /api/classes/:id': '删除班级（软删除，排课记录保留）',
        'GET /api/classes/:classId/students': '获取指定班级的学生列表',
        'POST /api/classes/:classId/students': '在指定班级下创建学生并自动关联到该班级',
        'DELETE /api/classes/:classId/students/:studentId': '从指定班级移除学生（仅解除关联，不删除学生实体）',
      },
      students: {
        'GET /api/students': '获取所有学生（含 classIds 数组）',
        'GET /api/students/by-class/:classId': '获取指定班级的学生列表',
        'POST /api/students': '创建学生（可通过 classIds 数组同时关联多个班级）',
        'PUT /api/students/:id': '更新学生信息',
        'DELETE /api/students/:id': '删除学生（同时清理所有班级关联）',
      },
      schedules: {
        'GET /api/schedules?start=YYYY-MM-DD&end=YYYY-MM-DD': '获取日期范围内的排课（含班级信息）',
        'GET /api/schedules?range=today|week|month': '快捷范围：today=今天，week=本周（周一到周日），month=本月。与 start/end 互斥',
        'GET /api/schedules?start=&end=&classId=N': '同上，额外按班级 ID 过滤（服务端过滤，节省流量）',
        'GET /api/schedules/:id': '获取单条排课详情（含班级信息）',
        'POST /api/schedules': '创建单次排课，返回完整排课对象（含 class 字段）；如有时间冲突，额外返回 warnings 数组（不阻止创建）',
        'PUT /api/schedules/:id': '更新排课，返回完整排课对象；时间变更时自动重算 durationBilling；如有冲突返回 warnings',
        'DELETE /api/schedules/:id': '删除单条排课',
        'DELETE /api/schedules/batch': '批量删除排课（见 batchDeleteModes）',
        'POST /api/schedules/batch': '批量创建排课（见 batchScheduleModes）',
        'PUT /api/schedules/batch': '批量更新排课时间/地点（见 batchUpdateMode）',
        'GET /api/schedules/summary?start=YYYY-MM-DD&end=YYYY-MM-DD': '课时与收入汇总统计（见 summaryResponse）；加 &format=csv 返回 CSV 文件（UTF-8 BOM，Excel 兼容）；加 &classId=1 或 &classId=1,2,3 按班级过滤',
        'GET /api/schedules/export?start=YYYY-MM-DD&end=YYYY-MM-DD': '导出排课明细列表（含班级信息）；加 &classId=N 过滤班级；加 &format=csv 返回 CSV',
        'GET /api/schedules/free-slots?date=YYYY-MM-DD': '查询单日空闲时段（默认 08:00-23:00；可用 after=HH:MM&before=HH:MM 限制时段）',
        'GET /api/schedules/free-slots?date=&minDuration=60': '只返回连续可用 ≥60 分钟的时段，适合约课筛选',
        'GET /api/schedules/free-slots?start=YYYY-MM-DD&end=YYYY-MM-DD': '查询多日空闲时段（同样支持 after/before/minDuration）',
        'GET /api/schedules/conflicts?start=YYYY-MM-DD&end=YYYY-MM-DD&limit=N': '查询冲突排课分组（默认今天起60天，limit 上限100，默认20）',
      },
      semesters: {
        'GET /api/semesters': '获取学期列表',
        'POST /api/semesters': '创建学期',
        'PUT /api/semesters/:id': '更新学期',
        'DELETE /api/semesters/:id': '删除学期',
      },
      holidays: {
        'GET /api/holidays': '获取所有节假日和调休记录',
        'GET /api/holidays/:year': '获取指定年份的节假日',
        'POST /api/holidays': '添加节假日/调休（需 date, type: holiday|workday, name）',
        'PUT /api/holidays/:id': '更新节假日记录',
        'DELETE /api/holidays/:id': '删除节假日记录',
        'POST /api/holidays/batch': '批量导入节假日（需 items 数组）',
      },
      pricingTiers: {
        'GET /api/pricing-tiers': '获取定价阶梯列表',
        'POST /api/pricing-tiers': '创建定价阶梯',
        'PUT /api/pricing-tiers/:id': '更新定价阶梯',
        'DELETE /api/pricing-tiers/:id': '删除定价阶梯',
      },
      images: {
        'GET /api/schedule-image?start=YYYY-MM-DD&end=YYYY-MM-DD': '生成课表 PNG 图片（返回 image/png），支持任意时间范围；失败时返回 JSON {error, detail}',
        'GET /api/schedule-image?range=today|week|month': '快捷范围，与 GET /api/schedules 的 range 参数一致',
        'GET /api/schedule-image?start=&end=&theme=light|dark|auto': 'theme=light 强制浅色，dark 强制深色，auto（默认）按小时自动切换（7:00-19:00 浅色，其余深色）',
        'GET /api/schedule-image?start=&end=&rowH=N': '每小时行高像素（16-60，默认 30），增大后文字更清晰，图片更高',
        'GET /api/schedule-image?start=&end=&scale=N': '整体缩放因子（0.25-3，默认 2），scale=1 适合手机查看，scale=0.5 更小体积',
        'GET /api/schedule-image?start=&end=&highlight=YYYY-MM-DD': '高亮指定日期列（黄色边框），适合截给家长看某天课表',
      },
      backup: {
        'GET /api/backup': '导出教师全量数据为 JSON（classes, students, schedules, semesters, holidays, pricingTiers, classStudents），触发浏览器下载',
        'POST /api/backup/restore': '从备份 JSON 原子还原（先清空再写入，事务保证）；teacherId 强制覆盖为当前认证教师，防止数据越权',
      },
      auditLog: {
        'GET /api/audit-log': '查询操作日志（默认最新 100 条）',
        'GET /api/audit-log?limit=N': '最多返回 N 条（上限 500）',
        'GET /api/audit-log?table=schedules': '按数据表过滤（schedules / classes）',
        'GET /api/audit-log?action=DELETE': '按操作类型过滤（CREATE / UPDATE / DELETE / BATCH_DELETE / BATCH_UPDATE）',
      },
    },
    batchScheduleModes: {
      semester: {
        description: '按学期 + 每周几自动生成排课，自动跳过法定节假日',
        params: {
          classId: '班级 ID（必填）',
          semesterId: '学期 ID（必填）',
          weekday: '星期几，0=周日，1=周一，...，6=周六（必填）',
          startTime: '开始时间 HH:MM（必填）',
          endTime: '结束时间 HH:MM（必填）',
          durationBilling: '计费时长分钟，留空自动计算（可选）',
        },
        response: '{ count: N, ids: [...] }',
      },
      dates: {
        description: '按指定日期列表批量排课，不自动跳过节假日',
        params: {
          classId: '班级 ID（必填）',
          dates: '日期数组 ["YYYY-MM-DD", ...]（必填）',
          startTime: '开始时间 HH:MM（必填）',
          endTime: '结束时间 HH:MM（必填）',
          durationBilling: '计费时长分钟，留空自动计算（可选）',
        },
        response: '{ count: N, ids: [...] }',
      },
    },
    batchDeleteModes: {
      byIds: {
        description: '按排课 ID 数组精确删除',
        body: '{ ids: [1, 2, 3, ...] }',
        response: '{ count: N }',
      },
      byDateRange: {
        description: '按日期范围删除（可附加 classId 只删指定班级）',
        body: '{ start: "YYYY-MM-DD", end: "YYYY-MM-DD", classId: N (可选) }',
        response: '{ count: N }',
      },
    },
    batchUpdateMode: {
      description: 'PUT /api/schedules/batch — 批量修改同一班级、同一星期几、指定日期之后所有排课的时间或地点',
      params: {
        classId: '班级 ID（必填）',
        fromDate: '起始日期 YYYY-MM-DD（含，必填）；只修改该日期及之后的课',
        weekday: '星期几，0=周日…6=周六（必填）；只修改该星期几的课',
        semesterOnly: '是否限制在学期范围内（boolean，默认 true）；设为 false 则不检查学期',
        updates: '要修改的字段对象（必填）；仅允许以下字段：startTime, endTime, durationBilling, locationName, locationLat, locationLng',
      },
      allowedUpdateFields: ['startTime', 'endTime', 'durationBilling', 'locationName', 'locationLat', 'locationLng'],
      note: 'startTime/endTime 变更时自动重算 durationBilling（除非 updates 中显式传 durationBilling）；不在 allowedUpdateFields 中的字段静默忽略',
      response: '{ count: N, ids: [...] }',
      example: '{"classId":1,"fromDate":"2026-05-01","weekday":6,"updates":{"startTime":"14:00","endTime":"16:00"}}',
    },
    summaryResponse: {
      description: 'GET /api/schedules/summary 返回结构；支持 &classId=N（逗号分隔多个）按班级过滤',
      fields: {
        count: '排课总次数',
        hours: '总教学课时（小时，含小数）',
        revenue: '预估总收入（元）',
        byClass: '按班级分组 [{classId, name, subject, grade, count, hours, revenue}]，按收入降序',
        bySubject: '按学科分组 [{subject, count, hours, revenue}]，按次数降序',
        byGrade: '按年级分组 [{grade, count, hours, revenue}]，按次数降序',
      },
      revenueFormula: '(unitPrice × studentCount - discountAmount) × (durationBilling 分钟 / 60)',
    },
    dataModels: {
      class: {
        name: '班级名称（必填）',
        grade: '年级：初一/初二/初三/高一/高二/高三/大学（必填）',
        subject: '学科（必填）',
        studentCount: '学生人数（必填）',
        unitPrice: '单价（元/人/小时），留空自动匹配阶梯定价',
        discountAmount: '优惠金额（默认 0）',
        discountReason: '优惠原因（可选）',
        isCompetition: '是否竞赛课（boolean，默认 false）',
        defaultLocationName: '默认上课地点名称',
        defaultLocationLat: '纬度',
        defaultLocationLng: '经度',
      },
      student: {
        name: '姓名（必填）',
        birthDate: '出生日期，可只填年份如 "2010"',
        phone: '学生电话',
        parentName: '父母姓名',
        parentPhone: '父母联系方式',
        note: '备注',
        classIds: '所属班级 ID 数组（创建/更新时可关联多个班级）',
      },
      schedule: {
        classId: '班级 ID（必填）',
        date: '上课日期 YYYY-MM-DD（必填）',
        startTime: '开始时间 HH:MM（必填）',
        endTime: '结束时间 HH:MM（必填）',
        durationBilling: '计费时长（分钟），默认由 endTime - startTime 自动计算，手动指定时覆盖',
        locationName: '上课地点名称（默认继承班级默认地点）',
        locationLat: '纬度',
        locationLng: '经度',
        createdAt: '创建时间（ISO 8601 格式，由数据库自动填写）',
      },
      semester: {
        name: '学期名称（如 "2026春季"）',
        type: '类型：spring / fall / winter / summer',
        startDate: '开始日期 YYYY-MM-DD',
        endDate: '结束日期 YYYY-MM-DD',
      },
      holiday: {
        date: '日期 YYYY-MM-DD',
        type: 'holiday（节假日）或 workday（调休上班）',
        name: '名称（如 "春节"、"国庆调休"）',
      },
      auditLogEntry: {
        id: '日志 ID',
        teacherId: '教师 ID',
        timestamp: '操作时间（ISO 8601）',
        action: 'CREATE / UPDATE / DELETE / BATCH_DELETE',
        tableName: '操作的数据表（schedules / classes）',
        recordId: '被操作记录的 ID（批量操作时为 null）',
        beforeData: '操作前数据对象（CREATE 时为 null）',
        afterData: '操作后数据对象（DELETE 时为 null，BATCH_DELETE 时含 count 和 ids）',
      },
    },
    notes: [
      '所有 JSON 响应的 Content-Type 均为 application/json; charset=utf-8',
      '排课冲突不会被服务端阻止，前端并排显示并红色高亮；可用 GET /api/schedules/conflicts 查询已有冲突',
      'GET /api/schedules 支持 range=today|week|month 快捷参数，week=本周周一到周日，与 start/end 互斥',
      'free-slots 支持 after/before 参数限制查询时段（如 after=14:00&before=21:00），优先级高于 dayStart/dayEnd；支持 minDuration=N 过滤（只返回连续可用 ≥N 分钟的时段）',
      'POST/PUT /api/schedules 返回的排课对象可能含 warnings 字段（数组），包含同一时段的冲突排课信息（id/classId/className/startTime/endTime），不阻止创建/更新',
      'conflicts 返回 {total, groups:[{date, schedules:[...]}]}，schedules 为同一天内互相重叠的排课组（每组至少2条）',
      'POST /api/schedules 和 PUT /api/schedules/:id 均返回完整排课对象（含 class 字段），可直接判断是否存在冲突',
      'durationBilling 默认由 endTime - startTime 自动计算，跨午夜时自动处理',
      '法定节假日数据可通过 POST /api/holidays/batch 批量导入，批量排课（学期模式）自动跳过',
      '图片导出支持任意时间范围，天数越多图片越宽；生成失败时返回 JSON 错误而非 HTML；rowH 范围 16-60，默认 30',
      'PUT /api/schedules/batch 只允许修改时间和地点字段，classId/date 等核心字段不可批量篡改',
      'GET /api/schedules/summary 和 GET /api/schedules/export 均支持 &format=csv，响应含 UTF-8 BOM，Excel 直接打开不乱码',
      'GET /api/backup 返回全量 JSON；POST /api/backup/restore 原子还原（事务），恢复过程中 teacherId 强制绑定当前账号',
      '学生可属于多个班级，通过 classIds 数组关联；DELETE /api/students/:id 删除学生实体并清理所有关联，DELETE /api/classes/:classId/students/:studentId 仅从指定班级移除',
      '所有写操作（排课增删改、班级增删改、批量操作）均自动写入 audit_log，可通过 GET /api/audit-log 查询',
      '注册成功后系统自动将 ALLOW_REGISTRATION 设为 false，单用户设计',
      '所有写接口均使用 express-validator 校验输入，校验失败返回 400 {error: "提示信息"}，详见下方 validationRules',
    ],
    validationRules: {
      auth: {
        register: { username: '3-20位字母数字', password: '至少6位', name: '必填' },
        login: { username: '必填', password: '必填' },
        changePassword: { oldPassword: '必填', newPassword: '至少6位' },
        updateSubjects: { subjects: '字符串数组，每项1-20字符' },
      },
      classes: {
        create: { name: '必填', grade: '枚举：初一/初二/初三/高一/高二/高三/大学', subject: '必填', studentCount: '≥1整数' },
        update: { name: '可选', grade: '可选枚举', subject: '可选', studentCount: '可选≥1' },
        addStudent: { name: '必填', phone: '11位手机号（可选）' },
      },
      students: {
        create: { name: '必填', phone: '11位手机号（可选）', birthDate: 'YYYY-MM-DD（可选）', classIds: '整数数组（可选）' },
        update: { name: '可选', phone: '可选11位', birthDate: '可选' },
      },
      schedules: {
        create: { classId: '整数必填', date: 'YYYY-MM-DD 必填', startTime: 'HH:MM 必填', endTime: 'HH:MM 必填' },
        batchCreate: { classId: '整数必填', startTime: 'HH:MM 必填', endTime: 'HH:MM 必填' },
        batchUpdate: { classId: '整数必填', fromDate: 'YYYY-MM-DD 必填', weekday: '0-6 必填', updates: '对象必填' },
        batchDelete: { ids: '整数数组，或 start+end 日期范围' },
      },
      semesters: {
        create: { name: '必填', type: '枚举：spring/fall/winter/summer（对应 春季/秋季/暑假/寒假）', startDate: 'YYYY-MM-DD 必填', endDate: 'YYYY-MM-DD 必填' },
        update: { name: '可选', type: '可选枚举', startDate: '可选', endDate: '可选' },
      },
      holidays: {
        create: { date: 'YYYY-MM-DD 必填', type: '枚举：holiday/workday', name: '必填' },
        update: { date: '可选', type: '可选枚举' },
        batch: { items: '数组，每项含 date/type/name' },
      },
      pricingTiers: {
        create: { minStudents: '≥1整数', maxStudents: '≥1整数', pricePerStudentPerHour: '>0 数字' },
        update: { minStudents: '可选≥1', maxStudents: '可选≥1', pricePerStudentPerHour: '可选>0' },
      },
    },
    examples: {
      '登录获取 token': 'POST /api/auth/login {"username":"xxx","password":"xxx"}',
      '获取本周课表（快捷）': 'GET /api/schedules?range=week',
      '获取今日课表': 'GET /api/schedules?range=today',
      '获取本月课表': 'GET /api/schedules?range=month',
      '获取本周课表（显式日期）': 'GET /api/schedules?start=2026-04-27&end=2026-05-03',
      '获取指定班级本周课表': 'GET /api/schedules?start=2026-04-27&end=2026-05-03&classId=1',
      '获取单条排课': 'GET /api/schedules/42',
      '本月收入汇总（JSON）': 'GET /api/schedules/summary?start=2026-05-01&end=2026-05-31',
      '本月收入汇总（按班级过滤）': 'GET /api/schedules/summary?start=2026-05-01&end=2026-05-31&classId=1',
      '本月收入汇总（CSV 下载）': 'GET /api/schedules/summary?start=2026-05-01&end=2026-05-31&format=csv',
      '导出排课明细（JSON）': 'GET /api/schedules/export?start=2026-05-01&end=2026-05-31',
      '导出排课明细（CSV 下载）': 'GET /api/schedules/export?start=2026-05-01&end=2026-05-31&format=csv',
      '批量调整排课时间（周六从5月起改为14:00-16:00）': 'PUT /api/schedules/batch {"classId":1,"fromDate":"2026-05-01","weekday":6,"updates":{"startTime":"14:00","endTime":"16:00"}}',
      '生成课表图片（默认）': 'GET /api/schedule-image?start=2026-04-27&end=2026-05-03',
      '生成课表图片（浅色，行高40）': 'GET /api/schedule-image?start=2026-04-27&end=2026-05-03&theme=light&rowH=40',
      '生成2周课表图片（深色）': 'GET /api/schedule-image?start=2026-04-27&end=2026-05-10&theme=dark',
      '批量排课（学期模式）': 'POST /api/schedules/batch {"classId":1,"semesterId":1,"weekday":1,"startTime":"08:00","endTime":"10:00"}',
      '批量排课（日期模式）': 'POST /api/schedules/batch {"classId":1,"dates":["2026-07-01","2026-07-08"],"startTime":"08:00","endTime":"10:00"}',
      '批量删课（ID数组）': 'DELETE /api/schedules/batch {"ids":[10,11,12]}',
      '批量删课（日期范围+班级）': 'DELETE /api/schedules/batch {"classId":1,"start":"2026-05-01","end":"2026-05-31"}',
      '查询空闲时段（全天）': 'GET /api/schedules/free-slots?date=2026-05-06',
      '查询空闲时段（指定时段）': 'GET /api/schedules/free-slots?date=2026-05-06&after=14:00&before=21:00',
      '查询空闲时段（至少60分钟）': 'GET /api/schedules/free-slots?date=2026-05-06&minDuration=60',
      '查询多日空闲时段（指定时段）': 'GET /api/schedules/free-slots?start=2026-05-06&end=2026-05-12&after=14:00&before=22:00',
      '生成本周课表图片（快捷）': 'GET /api/schedule-image?range=week',
      '生成课表图片（手机缩放）': 'GET /api/schedule-image?range=week&scale=1',
      '生成课表图片（高亮某天）': 'GET /api/schedule-image?range=week&highlight=2026-05-06',
      '获取全部班级（含已删除）': 'GET /api/classes?includeDeleted=true',
      '查询冲突排课': 'GET /api/schedules/conflicts',
      '查询近期冲突（自定义范围）': 'GET /api/schedules/conflicts?start=2026-05-01&end=2026-05-31&limit=50',
      '查询操作日志（最近批量操作）': 'GET /api/audit-log?action=BATCH_UPDATE&limit=20',
      '查询操作日志（最近删除）': 'GET /api/audit-log?table=schedules&action=DELETE&limit=20',
      '创建学生并关联多个班级': 'POST /api/students {"name":"张三","birthDate":"2010","classIds":[1,2]}',
      '在指定班级下创建学生': 'POST /api/classes/1/students {"name":"张三","phone":"13800138000"}',
      '从班级移除学生（不解绑其他班级）': 'DELETE /api/classes/1/students/5',
      '删除学生（级联删除所有关联）': 'DELETE /api/students/5',
      '创建学期': 'POST /api/semesters {"name":"2026春季","type":"spring","startDate":"2026-02-23","endDate":"2026-07-05"}',
      '批量导入节假日': 'POST /api/holidays/batch {"items":[{"date":"2026-01-01","type":"holiday","name":"元旦"}]}',
      '备份全量数据': 'GET /api/backup',
      '还原备份（传 GET /api/backup 的响应体）': 'POST /api/backup/restore <backup-json>',
    },
  });
});

export default router;
